### ISSUE TITLE
Issue with /dbm unlock

### ISSUE THREAD

**Issue by solarblazin** [Zidras/DBM-Icecrown#19]
/dbm unlock is pretty broken, it creates the "unlock" bar, but it is not movable and it also throws a LUA error

this happens even with only DBM being enabled

Lua error:
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:961: attempt to concatenate local 'text' (a nil value)
Time: 07/26/21 02:42:53
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:961: in function `SetText'
Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1239: in function `ShowMovableBar'
Interface\AddOns\DBM-Core\DBM-Core.lua:1668: in function `value'
Interface\FrameXML\ChatFrame.lua:4070: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Comment by solarblazin** [comment]
Ah, just messed around with code

Lines 1239 and 1243 need to be edited with DBM_CORE_MOVABLE_BAR changed to DBM_CORE_L.MOVABLE_BAR

**Comment by Zidras** [comment]
Looking at the code, I noticed infoframe is not being affected by this command. Will also look into it at a later time
