### ISSUE TITLE
DBM pull is not consistent with creating bar timers

### ISSUE THREAD

**Issue by Zidras** [Zidras/DBM-Icecrown#24]
**Describe the bug**
`/dbm pull` is not providing with either gold numbers or Bar Timer.

**To Reproduce**
1. `/dbm pull`

**Expected behavior**
![image](https://user-images.githubusercontent.com/10605951/128614436-061a3e58-da06-4360-b9d9-89899d116274.png)
![image](https://user-images.githubusercontent.com/10605951/128614441-55db4600-1227-4e7a-8435-54d7287e4b4e.png)

**Comment by Zidras** [comment]
For future reference, the reason the gold numbers weren't showing as well was because they are part of the delayed functions, which run after 10 seconds of ADDON_LOADED

**Comment by Barsoomx** [comment]
the hook should be moved somewhere else after the UI info is available, addon_loaded is a bad place so I had to append it to delayed functions

**Comment by Zidras** [comment]
> the hook should be moved somewhere else after the UI info is available, addon_loaded is a bad place so I had to append it to delayed functions

Any suggestions?
