### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by Zidras** [Zidras/DBM-Icecrown#26]
**Describe the bug**
Profiles are not working as intended. Not only do they not work globally, but also different profiles on the same character are not saving user options.

**To Reproduce**

https://user-images.githubusercontent.com/10605951/129426461-0514d3cb-1c4a-4920-93f9-9362e70ab207.mp4

**Comment by Zidras** [comment]
I also was able to replicate this bug on retail...

**Comment by Barsoomx** [comment]
Well the original author didn't consider using AceProfile, 

I think the profiles should be reworked or refactored to support double spec timers placement, retail doesn't do everything right y'know

**Comment by Zidras** [comment]
You mean like this? 
![image](https://user-images.githubusercontent.com/10605951/129452284-10fc23b2-baae-4ade-91b0-302a3da342cb.png)

**Comment by Barsoomx** [comment]
No, that's only for timer and announce settings, I mean the other settings in the right tab, responsible for frame placements and stuff
